version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: mysql.dockerfile
    command: ["wait", "mysql", "mysql_test"]
    working_dir: /app
    volumes:
      - type: bind
        source: ./tests/data
        target: /app/data
    environment:
      MYSQL_HOST: mydb
      MYSQL_PWD: pass
      MYSQL_DATABASE: acris
    depends_on:
      - mydb

  pgdb:
    image: postgres:13
    ports:
      - 5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: root
      PGDATA: /var/lib/postgresql/data/pgdata

  psql:
    build:
      context: .
      dockerfile: psql.dockerfile
    command: ["wait", "psql", "psql_test"]
    working_dir: /app
    volumes:
      - type: bind
        source: ./tests/data
        target: /app/data
    environment:
      PGHOST: pgdb
      PGUSER: root
      PGPASSWORD: pass
      PGDATABASE: root
    depends_on:
      - pgdb

  mydb:
    image: mysql:8.0
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--default-storage-engine=MyISAM",
      "--local-infile=ON"
    ]
    ports:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
