name: Docker compose tests

on: [push]

jobs:
  test-mysql:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Copy test data to data directory
        run: cp -r tests/data data

      - name: Build the mysql image
        run: docker-compose build
        env:
          COMPOSE_FILE: docker-compose.mysql.yml

      - name: Run the stack
        run: docker-compose up --exit-code-from acris-mysql
        env:
          COMPOSE_FILE: docker-compose.mysql.yml

  test-psql:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Copy test data to data directory
        run: cp -r tests/data data

      - name: Build the postgresql image
        run: docker-compose build
        env:
          COMPOSE_FILE: docker-compose.psql.yml

      - name: Run the stack
        run: docker-compose up --exit-code-from acris-psql
        env:
          COMPOSE_FILE: docker-compose.psql.yml
